=== dsouzarogerio/xml-completo/dtd-elementos/empresa.dtd
<!ELEMENT empresa (funcionarios)>
<!ELEMENT funcionarios (funcionario+)>
<!ELEMENT funcionario (nome, cargo, (idade | data-nascimento), dependentes?)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT cargo (#PCDATA)>
<!ELEMENT idade (#PCDATA)>
<!ELEMENT data-nascimento (#PCDATA)>
<!ELEMENT dependentes (dependente+)>
<!ELEMENT dependente (nome, parentesco)>
<!ELEMENT parentesco (#PCDATA)>

=== dsouzarogerio/xml-completo/dtd-elementos/empresa.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--  <!DOCTYPE empresa SYSTEM "empresa.dtd"> -->
<!DOCTYPE empresa [
<!ELEMENT empresa (funcionarios)>
<!ELEMENT funcionarios (funcionario+)>
<!ELEMENT funcionario (nome, cargo, (idade | data-nascimento), dependentes?)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT cargo (#PCDATA)>
<!ELEMENT idade (#PCDATA)>
<!ELEMENT data-nascimento (#PCDATA)>
<!ELEMENT dependentes (dependente+)>
<!ELEMENT dependente (nome, parentesco)>
<!ELEMENT parentesco (#PCDATA)>
]>
<empresa>
    <funcionarios>
        <funcionario>
            <nome>Carlos Santos</nome>
            <cargo>Gerente de produção</cargo>
            <idade>45</idade>
            <dependentes>
                <dependente>
                    <nome>Suzana Santos</nome>
                    <parentesco>Cônjuge</parentesco>
                </dependente>
                <dependente>
                    <nome>Rafael Santos</nome>
                    <parentesco>Filho</parentesco>
                </dependente>
            </dependentes>
        </funcionario>
        <funcionario>
            <nome>Felipe Silva</nome>
            <cargo>auxiliar de produção</cargo>
            <data-nascimento>1973-09-03</data-nascimento>
            <dependentes>
                <dependente>
                    <nome>Carla Silva</nome>
                    <parentesco>Cônjuge</parentesco>
                </dependente>
            </dependentes>
        </funcionario>
    </funcionarios>
</empresa>
