<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE receita[

<!ELEMENT receita (titulo, ingredientes, instrucoes)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT ingredientes (ingrediente+)>
<!ELEMENT ingrediente (#PCDATA)>
<!ELEMENT instrucoes (passo+)>
<!ELEMENT passo (#PCDATA)>

<!ATTLIST receita
                nome CDATA #REQUIRED
                tempo_de_preparo CDATA #REQUIRED
                tempo_de_cozimento CDATA #REQUIRED
                >

<!ATTLIST ingrediente
                quantidade CDATA #REQUIRED
                unidade (xicaras | gramas | colheres) #REQUIRED
                estado CDATA #IMPLIED
                >
]>
<receita nome="pão" tempo_de_preparo="5 minutos" tempo_de_cozimento="1 hora">
    <titulo>Pão simples</titulo>
    <ingredientes>
        <ingrediente quantidade="3" unidade="xicaras">Farinha</ingrediente>
        <ingrediente quantidade="7" unidade="gramas">Fermento</ingrediente>
        <ingrediente quantidade="1.5" unidade="xicaras" estado="morna">Água</ingrediente>
        <ingrediente quantidade="1" unidade="colheres">Sal</ingrediente>
    </ingredientes>
    <instrucoes>
        <passo>Misture todos os ingredientes e dissolva bem</passo>
        <passo>Cubra com um pano e deixe por uma hora em um local morno</passo>
        <passo>Misture novamente, coloque numa bandeja e asse num forno</passo>
    </instrucoes>
</receita>